namespace: infra

cockroachdb:
  statefulset:
    replicas: 3

  storage:
    persistentVolume:
      enabled: true
      size: 10Gi

  service:
    type: ClusterIP

  tls:
    enabled: true

  conf:
    prometheus:
      enabled: true
