apiVersion: v1
kind: Pod
metadata:
  name: cockroach-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: cockroach-client
spec:
  restartPolicy: Never
  containers:
    - name: cockroach
      image: cockroachdb/cockroach:v23.1.11
      command:
        - /bin/bash
        - -c
        - -- # keep it alive so you can exec in
        - sleep infinity
      volumeMounts:
        - name: client-certs
          mountPath: /cockroach-certs
  volumes:
    - name: client-certs
      secret:
        secretName: infra-cockroachdb-client-secret
